[context.staging]
    command = "npm run build-client-staging"

[[redirects]]
    from = "/api/*"
    to = "https://hoa-director.herokuapp.com/api/:splat"
    status = 200
    
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
